config/routes.rb
Playa::Application.routes.draw do
  resources :services

  resources :activities

  resources :schedules

  resources :tours

  resources :events

  resources :night_lives

  resources :shoppings

  resources :transports

  resources :locations

  resources :restaurants

  resources :hotels

  devise_for :venues
  devise_for :admins

  root :to => "services#index"

end

app/models/activity.rb
class Activity < ActiveRecord::Base
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/models/night_life.rb
class NightLife < ActiveRecord::Base
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
end

app/models/service.rb
class Service < ActiveRecord::Base
end

app/models/shopping.rb
class Shopping < ActiveRecord::Base
end

app/models/tour.rb
class Tour < ActiveRecord::Base
end

app/models/transport.rb
class Transport < ActiveRecord::Base
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/transports_controller.rb
class TransportsController < ApplicationController
  before_action :set_transport, only: [:show, :edit, :update, :destroy]

  # GET /transports
  # GET /transports.json
  def index
    @transports = Transport.all
  end

  # GET /transports/1
  # GET /transports/1.json
  def show
  end

  # GET /transports/new
  def new
    @transport = Transport.new
  end

  # GET /transports/1/edit
  def edit
  end

  # POST /transports
  # POST /transports.json
  def create
    @transport = Transport.new(transport_params)

    respond_to do |format|
      if @transport.save
        format.html { redirect_to @transport, notice: 'Transport was successfully created.' }
        format.json { render action: 'show', status: :created, location: @transport }
      else
        format.html { render action: 'new' }
        format.json { render json: @transport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transports/1
  # PATCH/PUT /transports/1.json
  def update
    respond_to do |format|
      if @transport.update(transport_params)
        format.html { redirect_to @transport, notice: 'Transport was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @transport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transports/1
  # DELETE /transports/1.json
  def destroy
    @transport.destroy
    respond_to do |format|
      format.html { redirect_to transports_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transport
      @transport = Transport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transport_params
      params.require(:transport).permit(:type, :tel, :cel, :mail, :contactp, :contactt)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/shoppings_helper.rb
module ShoppingsHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/helpers/transports_helper.rb
module TransportsHelper
end

app/views/transports/_form.html.erb
<%= form_for(@transport) do |f| %>
  <% if @transport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transport.errors.count, "error") %> prohibited this transport from being saved:</h2>

      <ul>
      <% @transport.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :tel %><br>
    <%= f.text_field :tel %>
  </div>
  <div class="field">
    <%= f.label :cel %><br>
    <%= f.text_field :cel %>
  </div>
  <div class="field">
    <%= f.label :mail %><br>
    <%= f.text_field :mail %>
  </div>
  <div class="field">
    <%= f.label :contactp %><br>
    <%= f.text_field :contactp %>
  </div>
  <div class="field">
    <%= f.label :contactt %><br>
    <%= f.text_field :contactt %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transports/edit.html.erb
<h1>Editing transport</h1>

<%= render 'form' %>

<%= link_to 'Show', @transport %> |
<%= link_to 'Back', transports_path %>

app/views/transports/index.html.erb
<h1>Listing transports</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Tel</th>
      <th>Cel</th>
      <th>Mail</th>
      <th>Contactp</th>
      <th>Contactt</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @transports.each do |transport| %>
      <tr>
        <td><%= transport.type %></td>
        <td><%= transport.tel %></td>
        <td><%= transport.cel %></td>
        <td><%= transport.mail %></td>
        <td><%= transport.contactp %></td>
        <td><%= transport.contactt %></td>
        <td><%= link_to 'Show', transport %></td>
        <td><%= link_to 'Edit', edit_transport_path(transport) %></td>
        <td><%= link_to 'Destroy', transport, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transport', new_transport_path %>

app/views/transports/new.html.erb
<h1>New transport</h1>

<%= render 'form' %>

<%= link_to 'Back', transports_path %>

app/views/transports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @transport.type %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @transport.tel %>
</p>

<p>
  <strong>Cel:</strong>
  <%= @transport.cel %>
</p>

<p>
  <strong>Mail:</strong>
  <%= @transport.mail %>
</p>

<p>
  <strong>Contactp:</strong>
  <%= @transport.contactp %>
</p>

<p>
  <strong>Contactt:</strong>
  <%= @transport.contactt %>
</p>

<%= link_to 'Edit', edit_transport_path(@transport) %> |
<%= link_to 'Back', transports_path %>