config/routes.rb
Playa::Application.routes.draw do
  resources :services

  resources :activities

  resources :schedules

  resources :tours

  resources :events

  resources :night_lives

  resources :shoppings

  resources :transports

  resources :locations

  resources :restaurants

  resources :hotels

  devise_for :venues
  devise_for :admins

  root :to => "services#index"

end

app/models/activity.rb
class Activity < ActiveRecord::Base
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/models/night_life.rb
class NightLife < ActiveRecord::Base
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
end

app/models/service.rb
class Service < ActiveRecord::Base
end

app/models/shopping.rb
class Shopping < ActiveRecord::Base
end

app/models/tour.rb
class Tour < ActiveRecord::Base
end

app/models/transport.rb
class Transport < ActiveRecord::Base
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render action: 'show', status: :created, location: @schedule }
      else
        format.html { render action: 'new' }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :sunday)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/shoppings_helper.rb
module ShoppingsHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/helpers/transports_helper.rb
module TransportsHelper
end

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :monday %><br>
    <%= f.text_field :monday %>
  </div>
  <div class="field">
    <%= f.label :tuesday %><br>
    <%= f.text_field :tuesday %>
  </div>
  <div class="field">
    <%= f.label :wednesday %><br>
    <%= f.text_field :wednesday %>
  </div>
  <div class="field">
    <%= f.label :thursday %><br>
    <%= f.text_field :thursday %>
  </div>
  <div class="field">
    <%= f.label :friday %><br>
    <%= f.text_field :friday %>
  </div>
  <div class="field">
    <%= f.label :saturday %><br>
    <%= f.text_field :saturday %>
  </div>
  <div class="field">
    <%= f.label :sunday %><br>
    <%= f.text_field :sunday %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<h1>Listing schedules</h1>

<table>
  <thead>
    <tr>
      <th>Monday</th>
      <th>Tuesday</th>
      <th>Wednesday</th>
      <th>Thursday</th>
      <th>Friday</th>
      <th>Saturday</th>
      <th>Sunday</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.monday %></td>
        <td><%= schedule.tuesday %></td>
        <td><%= schedule.wednesday %></td>
        <td><%= schedule.thursday %></td>
        <td><%= schedule.friday %></td>
        <td><%= schedule.saturday %></td>
        <td><%= schedule.sunday %></td>
        <td><%= link_to 'Show', schedule %></td>
        <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
        <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<h1>New schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Monday:</strong>
  <%= @schedule.monday %>
</p>

<p>
  <strong>Tuesday:</strong>
  <%= @schedule.tuesday %>
</p>

<p>
  <strong>Wednesday:</strong>
  <%= @schedule.wednesday %>
</p>

<p>
  <strong>Thursday:</strong>
  <%= @schedule.thursday %>
</p>

<p>
  <strong>Friday:</strong>
  <%= @schedule.friday %>
</p>

<p>
  <strong>Saturday:</strong>
  <%= @schedule.saturday %>
</p>

<p>
  <strong>Sunday:</strong>
  <%= @schedule.sunday %>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>