config/routes.rb
Playa::Application.routes.draw do
  resources :services

  resources :activities

  resources :schedules

  resources :tours

  resources :events

  resources :night_lives

  resources :shoppings

  resources :transports

  resources :locations

  resources :restaurants

  resources :hotels

  devise_for :venues
  devise_for :admins

  root :to => "services#index"

end

app/models/activity.rb
class Activity < ActiveRecord::Base
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/models/night_life.rb
class NightLife < ActiveRecord::Base
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
end

app/models/service.rb
class Service < ActiveRecord::Base
end

app/models/shopping.rb
class Shopping < ActiveRecord::Base
end

app/models/tour.rb
class Tour < ActiveRecord::Base
end

app/models/transport.rb
class Transport < ActiveRecord::Base
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/shoppings_controller.rb
class ShoppingsController < ApplicationController
  before_action :set_shopping, only: [:show, :edit, :update, :destroy]

  # GET /shoppings
  # GET /shoppings.json
  def index
    @shoppings = Shopping.all
  end

  # GET /shoppings/1
  # GET /shoppings/1.json
  def show
  end

  # GET /shoppings/new
  def new
    @shopping = Shopping.new
  end

  # GET /shoppings/1/edit
  def edit
  end

  # POST /shoppings
  # POST /shoppings.json
  def create
    @shopping = Shopping.new(shopping_params)

    respond_to do |format|
      if @shopping.save
        format.html { redirect_to @shopping, notice: 'Shopping was successfully created.' }
        format.json { render action: 'show', status: :created, location: @shopping }
      else
        format.html { render action: 'new' }
        format.json { render json: @shopping.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shoppings/1
  # PATCH/PUT /shoppings/1.json
  def update
    respond_to do |format|
      if @shopping.update(shopping_params)
        format.html { redirect_to @shopping, notice: 'Shopping was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @shopping.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shoppings/1
  # DELETE /shoppings/1.json
  def destroy
    @shopping.destroy
    respond_to do |format|
      format.html { redirect_to shoppings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shopping
      @shopping = Shopping.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shopping_params
      params.require(:shopping).permit(:type, :tel, :mail, :contactp, :contactt, :products)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/shoppings_helper.rb
module ShoppingsHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/helpers/transports_helper.rb
module TransportsHelper
end

app/views/shoppings/_form.html.erb
<%= form_for(@shopping) do |f| %>
  <% if @shopping.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shopping.errors.count, "error") %> prohibited this shopping from being saved:</h2>

      <ul>
      <% @shopping.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :tel %><br>
    <%= f.text_field :tel %>
  </div>
  <div class="field">
    <%= f.label :mail %><br>
    <%= f.text_field :mail %>
  </div>
  <div class="field">
    <%= f.label :contactp %><br>
    <%= f.text_field :contactp %>
  </div>
  <div class="field">
    <%= f.label :contactt %><br>
    <%= f.text_field :contactt %>
  </div>
  <div class="field">
    <%= f.label :products %><br>
    <%= f.text_area :products %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shoppings/edit.html.erb
<h1>Editing shopping</h1>

<%= render 'form' %>

<%= link_to 'Show', @shopping %> |
<%= link_to 'Back', shoppings_path %>

app/views/shoppings/index.html.erb
<h1>Listing shoppings</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Tel</th>
      <th>Mail</th>
      <th>Contactp</th>
      <th>Contactt</th>
      <th>Products</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @shoppings.each do |shopping| %>
      <tr>
        <td><%= shopping.type %></td>
        <td><%= shopping.tel %></td>
        <td><%= shopping.mail %></td>
        <td><%= shopping.contactp %></td>
        <td><%= shopping.contactt %></td>
        <td><%= shopping.products %></td>
        <td><%= link_to 'Show', shopping %></td>
        <td><%= link_to 'Edit', edit_shopping_path(shopping) %></td>
        <td><%= link_to 'Destroy', shopping, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shopping', new_shopping_path %>

app/views/shoppings/new.html.erb
<h1>New shopping</h1>

<%= render 'form' %>

<%= link_to 'Back', shoppings_path %>

app/views/shoppings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @shopping.type %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @shopping.tel %>
</p>

<p>
  <strong>Mail:</strong>
  <%= @shopping.mail %>
</p>

<p>
  <strong>Contactp:</strong>
  <%= @shopping.contactp %>
</p>

<p>
  <strong>Contactt:</strong>
  <%= @shopping.contactt %>
</p>

<p>
  <strong>Products:</strong>
  <%= @shopping.products %>
</p>

<%= link_to 'Edit', edit_shopping_path(@shopping) %> |
<%= link_to 'Back', shoppings_path %>